project: 
  type: website
  
website: 
  favicon: images/favicon.ico
  page-navigation: true
  title: "A Biomedical Visualization Atlas" 
  site-url: "https://martinahyang.github.io/Toolkit/" 
  repo-url: https://github.com/MartinaHYang/Toolkit
  repo-actions:
    - source
    - issue
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Peng Lab, 2024. All rights reserved."
    
  sidebar:
    logo: "images/Bizard_logo.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/DrRobinLuo/Bizard
        text: "Bizard GitHub website"
      - icon: twitter
        href: https://x.com/PengL_Robin
        text: "Peng Lab Twitter"
      - icon: translate       

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Welcome"
        text-zh-cn: "简介"
        href: index.qmd
      - text: "Graph Gallery"
        text-zh-cn: "可视化一览"
        href: Graph-Gallery.qmd
      - section: "Distribution"
        section-zh-cn: "数据分布可视化"
        contents: 
          - text: "Histogram"
            text-zh-cn: "直方图"
            href: Distribution/Histogram.qmd
      - text: "About Us"
        text-zh-cn: "关于我们"
        href: About.qmd
        


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto
  
comments:
  giscus:
    repo: "DrRobinLuo/Bizard"
    repo-id: "R_kgDONWVY7Q"
    category: "Announcements"
    category-id: "DIC_kwDONWVY7c4ClcJT"
    mapping: "pathname"
    reactions-enabled: true
    input-position: "top"
    theme: "preferred_color_scheme"
    loading: "lazy"

babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: zh-cn
    text: "简体中文"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['zh-cn']
title-zh-cn: 生物医学可视化百科
lang: en
