project: 
  type: website
  
website: 
  page-navigation: true
  title: "Code ToolKit" 
  site-url: "https://martinahyang.github.io/Toolkit/" 
  repo-url: https://github.com/MartinaHYang/Toolkit 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Peng Lab, 2024. All rights reserved."
    
  sidebar:
    logo: "images/CodeToolKit_logo.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/MartinaHYang/Toolkit
        text: "Code ToolKit website tutorial"
      - icon: twitter
        href: https://x.com/PengL_Robin
        text: "Peng Lab Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: Graph-Gallery.qmd
        text: Graph Gallery
      - section: Distribution-Gallery_sec/index.qmd
        contents: 
          - Distribution-Gallery_sec/histogram.qmd
      - href: About.qmd
        text: About Us


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
